stages:
- stage: Windows
  pool:
    vmImage: VS2017-Win2016
  jobs:
  - job: win_x64
    variables:
      VSCODE_ARCH: x64
    steps:
      - template: windows.yml
  - job: win_ia32
    variables:
      VSCODE_ARCH: ia32
    steps:
      - template: windows.yml
- stage: Linux
  dependsOn: []
  pool:
    vmImage: "Ubuntu-18.04"
  jobs:
  - job: linux_x64
    variables:
      VSCODE_ARCH: x64
    steps:
      - template: posix.yml
- stage: Mac
  dependsOn: []
  pool:
    vmImage: macOS-latest
  jobs:
  - job: mac_x64
    variables:
      VSCODE_ARCH: x64
    steps:
      - template: posix.yml

trigger:
  branches:
   include:
   - main